// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streamrpc_test.proto

package neroao.demobox.grpcdemo.streamrpc;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streamrpc.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
