// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streamrpc_test.proto

package neroao.demobox.grpcdemo.streamrpc;

public interface MessageCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streamrpc.MessageCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
