// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streamrpc_test.proto

package neroao.demobox.grpcdemo.streamrpc;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streamrpc.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string repMessage = 1;</code>
   */
  java.lang.String getRepMessage();
  /**
   * <code>optional string repMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getRepMessageBytes();
}
