// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streamrpc_test.proto

package neroao.demobox.grpcdemo.streamrpc;

public interface ResponseSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streamrpc.ResponseSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string messageCount = 1;</code>
   */
  java.lang.String getMessageCount();
  /**
   * <code>optional string messageCount = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageCountBytes();
}
