// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streamrpc_test.proto

package neroao.demobox.grpcdemo.streamrpc;

public interface SomebodyNamesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streamrpc.SomebodyNames)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string names = 1;</code>
   */
  java.lang.String getNames();
  /**
   * <code>optional string names = 1;</code>
   */
  com.google.protobuf.ByteString
      getNamesBytes();
}
