// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streamrpc_test.proto

package neroao.demobox.grpcdemo.streamrpc;

/**
 * Protobuf type {@code streamrpc.SomebodyNames}
 */
public  final class SomebodyNames extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:streamrpc.SomebodyNames)
    SomebodyNamesOrBuilder {
  // Use SomebodyNames.newBuilder() to construct.
  private SomebodyNames(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SomebodyNames() {
    names_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SomebodyNames(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            names_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return neroao.demobox.grpcdemo.streamrpc.StreamRpcProto.internal_static_streamrpc_SomebodyNames_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return neroao.demobox.grpcdemo.streamrpc.StreamRpcProto.internal_static_streamrpc_SomebodyNames_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            neroao.demobox.grpcdemo.streamrpc.SomebodyNames.class, neroao.demobox.grpcdemo.streamrpc.SomebodyNames.Builder.class);
  }

  public static final int NAMES_FIELD_NUMBER = 1;
  private volatile java.lang.Object names_;
  /**
   * <code>optional string names = 1;</code>
   */
  public java.lang.String getNames() {
    java.lang.Object ref = names_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      names_ = s;
      return s;
    }
  }
  /**
   * <code>optional string names = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNamesBytes() {
    java.lang.Object ref = names_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      names_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNamesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, names_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNamesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, names_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof neroao.demobox.grpcdemo.streamrpc.SomebodyNames)) {
      return super.equals(obj);
    }
    neroao.demobox.grpcdemo.streamrpc.SomebodyNames other = (neroao.demobox.grpcdemo.streamrpc.SomebodyNames) obj;

    boolean result = true;
    result = result && getNames()
        .equals(other.getNames());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NAMES_FIELD_NUMBER;
    hash = (53 * hash) + getNames().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(neroao.demobox.grpcdemo.streamrpc.SomebodyNames prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code streamrpc.SomebodyNames}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:streamrpc.SomebodyNames)
      neroao.demobox.grpcdemo.streamrpc.SomebodyNamesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return neroao.demobox.grpcdemo.streamrpc.StreamRpcProto.internal_static_streamrpc_SomebodyNames_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return neroao.demobox.grpcdemo.streamrpc.StreamRpcProto.internal_static_streamrpc_SomebodyNames_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              neroao.demobox.grpcdemo.streamrpc.SomebodyNames.class, neroao.demobox.grpcdemo.streamrpc.SomebodyNames.Builder.class);
    }

    // Construct using neroao.demobox.grpcdemo.streamrpc.SomebodyNames.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      names_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return neroao.demobox.grpcdemo.streamrpc.StreamRpcProto.internal_static_streamrpc_SomebodyNames_descriptor;
    }

    public neroao.demobox.grpcdemo.streamrpc.SomebodyNames getDefaultInstanceForType() {
      return neroao.demobox.grpcdemo.streamrpc.SomebodyNames.getDefaultInstance();
    }

    public neroao.demobox.grpcdemo.streamrpc.SomebodyNames build() {
      neroao.demobox.grpcdemo.streamrpc.SomebodyNames result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public neroao.demobox.grpcdemo.streamrpc.SomebodyNames buildPartial() {
      neroao.demobox.grpcdemo.streamrpc.SomebodyNames result = new neroao.demobox.grpcdemo.streamrpc.SomebodyNames(this);
      result.names_ = names_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof neroao.demobox.grpcdemo.streamrpc.SomebodyNames) {
        return mergeFrom((neroao.demobox.grpcdemo.streamrpc.SomebodyNames)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(neroao.demobox.grpcdemo.streamrpc.SomebodyNames other) {
      if (other == neroao.demobox.grpcdemo.streamrpc.SomebodyNames.getDefaultInstance()) return this;
      if (!other.getNames().isEmpty()) {
        names_ = other.names_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      neroao.demobox.grpcdemo.streamrpc.SomebodyNames parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (neroao.demobox.grpcdemo.streamrpc.SomebodyNames) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object names_ = "";
    /**
     * <code>optional string names = 1;</code>
     */
    public java.lang.String getNames() {
      java.lang.Object ref = names_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        names_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string names = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNamesBytes() {
      java.lang.Object ref = names_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        names_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string names = 1;</code>
     */
    public Builder setNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      names_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string names = 1;</code>
     */
    public Builder clearNames() {
      
      names_ = getDefaultInstance().getNames();
      onChanged();
      return this;
    }
    /**
     * <code>optional string names = 1;</code>
     */
    public Builder setNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      names_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:streamrpc.SomebodyNames)
  }

  // @@protoc_insertion_point(class_scope:streamrpc.SomebodyNames)
  private static final neroao.demobox.grpcdemo.streamrpc.SomebodyNames DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new neroao.demobox.grpcdemo.streamrpc.SomebodyNames();
  }

  public static neroao.demobox.grpcdemo.streamrpc.SomebodyNames getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SomebodyNames>
      PARSER = new com.google.protobuf.AbstractParser<SomebodyNames>() {
    public SomebodyNames parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SomebodyNames(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SomebodyNames> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SomebodyNames> getParserForType() {
    return PARSER;
  }

  public neroao.demobox.grpcdemo.streamrpc.SomebodyNames getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

