// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streamrpc_test.proto

package neroao.demobox.grpcdemo.streamrpc;

public final class StreamRpcProto {
  private StreamRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamrpc_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamrpc_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamrpc_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamrpc_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamrpc_SomebodyNames_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamrpc_SomebodyNames_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamrpc_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamrpc_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamrpc_ResponseSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamrpc_ResponseSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamrpc_MessageCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamrpc_MessageCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024streamrpc_test.proto\022\tstreamrpc\"/\n\016Req" +
      "uestMessage\022\014\n\004name\030\001 \001(\t\022\017\n\007message\030\002 \001" +
      "(\t\"%\n\017ResponseMessage\022\022\n\nrepMessage\030\001 \001(" +
      "\t\"\036\n\rSomebodyNames\022\r\n\005names\030\001 \001(\t\"\032\n\007Mes" +
      "sage\022\017\n\007message\030\001 \001(\t\"\'\n\017ResponseSummary" +
      "\022\024\n\014messageCount\030\001 \001(\t\"-\n\014MessageCount\022\014" +
      "\n\004name\030\001 \001(\t\022\017\n\007message\030\002 \001(\t2\236\002\n\tStream" +
      "Rpc\022>\n\003say\022\031.streamrpc.RequestMessage\032\032." +
      "streamrpc.ResponseMessage\"\000\022A\n\rsayToSome" +
      "Body\022\030.streamrpc.SomebodyNames\032\022.streamr",
      "pc.Message\"\0000\001\022H\n\013someBodySay\022\031.streamrp" +
      "c.RequestMessage\032\032.streamrpc.ResponseSum" +
      "mary\"\000(\001\022D\n\nStreamChat\022\027.streamrpc.Messa" +
      "geCount\032\027.streamrpc.MessageCount\"\000(\0010\001B5" +
      "\n!neroao.demobox.grpcdemo.streamrpcB\016Str" +
      "eamRpcProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_streamrpc_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streamrpc_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamrpc_RequestMessage_descriptor,
        new java.lang.String[] { "Name", "Message", });
    internal_static_streamrpc_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_streamrpc_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamrpc_ResponseMessage_descriptor,
        new java.lang.String[] { "RepMessage", });
    internal_static_streamrpc_SomebodyNames_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_streamrpc_SomebodyNames_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamrpc_SomebodyNames_descriptor,
        new java.lang.String[] { "Names", });
    internal_static_streamrpc_Message_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_streamrpc_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamrpc_Message_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_streamrpc_ResponseSummary_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_streamrpc_ResponseSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamrpc_ResponseSummary_descriptor,
        new java.lang.String[] { "MessageCount", });
    internal_static_streamrpc_MessageCount_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_streamrpc_MessageCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamrpc_MessageCount_descriptor,
        new java.lang.String[] { "Name", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
